const Routes = {
  LOADING: 'LOADING',

  LOGIN_STACK: 'LOGIN_STACK',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  SIGNUP_SCREEN: 'SIGNUP_SCREEN',
  PASSWORD_SETUP_SCREEN: 'PASSWORD_SETUP_SCREEN',
  MAIN_APP: 'MAIN_APP', //DRAWER

  APP_INTRO: 'SPLASH_SCREEN',

  HOME_STACK: 'HOME_STACK', // HOMESTACK CONTAINER FOR TABS
  HOME_TABS: 'HOME_TABS', //HOME TABS

  HOME_SCREEN: 'HOME',
  PROFILE_SCREEN: 'STUDENTS',
  NOTIFICATION_SCREEN: 'NOTIFICATIONS',

  LEAD_LIST_SCREEN: 'LIST_LEAD',
  LEAD_SCREEN: 'LEAD',

  FOLLOW_UP_LIST_SCREEN: 'FOLLOW_UP_LIST',
  FOLLOW_UP_FORM_SCREEN: 'FOLLOW_UP_FORM',

  TEST_RIDE_LIST_SCREEN: 'TEST_RIDE_LIST',

  BOOKING_LIST_SCREEN: 'BOOKING_LIST',

  OPPORTUNITY_SCREEN: 'OPPORTUNITY',
  TEST_RIDE_FORM_SCREEN: 'TEST_RIDE_FORM',
  BOOKING_FORM_SCREEN: 'BOOKING_FORM',

};

export default Routes;
